trigger:
- main

pool:
  vmImage: ubuntu-latest
  #vmImage: ubuntu-22.04

variables:
- group: New variable group 27-Jul

- name: solution
  value: '**/*.sln'

- name: buildPlatform
  value: 'Any CPU'

- name: buildConfiguration
  value: 'Release'

- name: NUGET_PACKAGES
  value: $(Agent.TempDirectory)/.nuget/packages


steps:

# ---------------------------------------------------------
# Install .NET 8 SDK (UseDotNet wirkt nur für direkte dotnet-Befehle)
# ---------------------------------------------------------
#- task: UseDotNet@2
#  displayName: Install .NET SDK 8
#  inputs:
#    packageType: sdk
#    version: 8.0.x

# ---------------------------------------------------------
# Path overwrite
# ---------------------------------------------------------
#- script: |
#    echo "##vso[task.prependpath]/home/vsts/.dotnet"
#  displayName: Override PATH for dotnet


# ---------------------------------------------------------
# Restore (direkt, NICHT DotNetCoreCLI)
# ---------------------------------------------------------
#- script: |
#    dotnet restore SampleDataAccessApi.sln
#  displayName: Restore packages

# ---------------------------------------------------------
# Restore
# ---------------------------------------------------------
- task: DotNetCoreCLI@2
  displayName: Restore packages
  inputs:
    command: restore
    projects: '$(solution)'

# ---------------------------------------------------------
# Build (direkt, NICHT DotNetCoreCLI)
# ---------------------------------------------------------
#- script: |
#    dotnet build SampleDataAccessApi.sln --configuration Release
#  displayName: Build solution
# ---------------------------------------------------------
# Build
# ---------------------------------------------------------
- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: build
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'


#- script: |
#    dotnet --version
#    dotnet restore SampleDataAccessApi.sln
#    dotnet build SampleDataAccessApi.sln --configuration Release
#  displayName: Restore + Build (direct)


# Install EF Toolsgit add
- script: |
    dotnet tool install --global dotnet-ef
  displayName: Install EF Tools

# ---------------------------------------------------------
# Build EF Core migration bundle
# we provide the path SampleDataAccessApi/SampleDataAccessApi.csproj.
# if missing it will sacnn all projects in the working directory and can be confused with some files that look like projects but they are not (ex: dcproj files)
# ---------------------------------------------------------
#- script: |
#    echo "Listing repo structure..."
#    ls -R .
#  displayName: Debug List repo structure
# ---------------------------------------------------------
# 1. Build EF migration bundle
# ---------------------------------------------------------
- script: |
    cd SampleDataAccessApi
    dotnet ef migrations bundle --output ../efbundle
  displayName: Build EF migration bundle

# ---------------------------------------------------------
# 2. Make bundle executable
# ---------------------------------------------------------
- script: |
    chmod +x efbundle
  displayName: Make EF bundle executable

# ---------------------------------------------------------
# 3. Run EF migration bundle
# ---------------------------------------------------------
- script: |
    ./efbundle --connection "$(sampleDataAccessApiDBConnectionstring)"
  displayName: Run EF migration bundle


# ---------------------------------------------------------
# Test + Coverage
# ---------------------------------------------------------
- script: |
    dotnet test SampleDataAccessApi.sln --configuration Release --collect:"XPlat Code Coverage"
  displayName: Run tests with coverage

# ---------------------------------------------------------
# Publish coverage
# ---------------------------------------------------------
- task: PublishCodeCoverageResults@1
  displayName: Publish coverage
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
    reportDirectory: '$(Agent.TempDirectory)'

# ---------------------------------------------------------
# Build Docker image
# ---------------------------------------------------------
- task: Docker@2
  displayName: Build Docker image
  inputs:
    command: build
    Dockerfile: Dockerfile
    repository: $(DOCKERHUB_USERNAME)/sampledataaccessapi
    tags: |
      latest

# ---------------------------------------------------------
# Login to Docker Hub
# ---------------------------------------------------------
- script: |
    echo "TOKEN: $(DOCKERHUB_TOKEN)"
    echo "USERNAME: $(DOCKERHUB_USERNAME)"
  displayName: Debug DockerHub variables

- script: |
    echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  displayName: Docker Hub Login

# ---------------------------------------------------------
# Push Docker image
# ---------------------------------------------------------
- script: |
    docker push $(DOCKERHUB_USERNAME)/sampledataaccessapi:latest
  displayName: Push Docker image

# ---------------------------------------------------------
# Update ACA image
# ---------------------------------------------------------
- task: AzureCLI@2
  displayName: Update ACA image
  inputs:
    azureSubscription: 'SampleDataAccessApi_ServiceConnection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az containerapp update \
        --name sampledataaccessapi \
        --resource-group SampleAccessDataApi_rg \
        --image docker.io/$(DOCKERHUB_USERNAME)/sampledataaccessapi:latest
